app/app.go

Fixed: #Port cap goes missing after restart
app/app.go
add "app.CapabilityKeeper.InitializeAndSeal(ctx)" in app/app.go which restores capability memStore

add sealandinitialize

---

go.sum
yoda/execute.go
yoda/gas.go
yoda/run.go

Currently, gas estimation for Yoda has been inaccurate since new Cosmos SDK version 0.40.0 due to changes of codec library with some tweaks of data structure occurred in Cosmos SDK.
Therefore, This MR fixes Yoda gas estimation algorithm by going through procedures that are required for submitting `MsgReportData` transaction, and estimate the gas used based on the procedures.
During analyzing the procedures, we have found that data size of `Account` in `auth` module has been increased due to changing of data structure, which causes `out of gas` when submitting the transaction. And, additional step has been added to a handler of `MsgReportData` which uses `HAS` store operation that cost the gas of 1000.
Therefore, this PR increase gas limit to support higher data size and more operations …

Fix Yoda Gas Estimation

---

Makefile

When typing `bandd version --long`, the server name shows `<appd>` instead of `bandd`.
This is because variable name in `version` package of Cosmos SDK is changed from `ServerName` to `AppName`.
Fixed: #XXXX
Rename `ServerName` to `AppName` during setting up ldflags.

Fix app name for `version` package

---

x/oracle/client/cli/query.go

Added a missing CLI command for querying validator status
```bash
bandd query oracle validator [bandvaloper-address]
```
Fixed: [BAND-390](https://bandprotocol.atlassian.net/browse/BAND-390)
The PR just add missing CLI command so, the source code can describe itself.

CLI command for querying validator status

---

app/app.go
app/hook.go

Fixed: -
Refactor Hooks to use `Hooks` type to represent a list of `Hook`. This makes the code less coupling.

Refactor Hooks (by Bun)

---

yoda/execute.go

Fixed: -
The account got from BandChain node has been reused, which should not happen. When there is out-of-gas scenario and trying to do another attempt, same account information has been used. However, sequence number of the account already changed and account information should be updated.
Otherwise, when sending the transaction, it will be rejected during CheckTx, and Yoda is unable to fetch the transaction status from BandChain
Every time when need account information, it should be always queried from BandChain node without reusing it.

Yoda Fix No-Reuse Account Information

---

x/oracle/keeper/result.go
x/oracle/types/msgs.go

- Add maxOwasmGas for validate basic on MsgRequestData, not you gas too much
- Explicit response packet timeout.

Limit prepare execute gas

---

app/app.go

Fixed: -
Since BaseApp.Query() remember return types of gRPC's methods, before returning result back to the client, using ApplyQuery() without calling `BaseApp.Query()` prevent gRPC server to get return type of the data.

Fix ApplyQuery to Remember Return Type

---

yoda/execute.go
yoda/gas.go
yoda/run.go

- Add retry logic when query data via ABCIQuery.
- Remove getting account when trying to estimate gas to reduce load to node and make code more simple.
- Filter only request type transactions

(yoda) Add retry logic when query data from node

---

CHANGELOG.md
app/app.go
go.mod
go.sum

Upgrade cosmos-sdk to v0.42.9 to resolve IBC channel restart issue.

Bump cosmos-sdk dependency

---

CHANGELOG.md
cmd/bandd/cmd/init.go
cmd/bandd/cmd/migrate.go

- Set block size to 1M
- Set block gas limit to 8M to prevent tx spamming to slow our chain

(app) Adjust block params on init and migrate command

---

CHANGELOG.md
yoda/handler.go

Due to requests from IBC, there are msgs that come with on receive msg that make yoda try to find request id from all message on got error log that cannot find request id.

(yoda) Fix false alarm error when search request id on event log

---

flusher/flusher/db.py
flusher/flusher/handler.py
flusher/flusher/init.py
hasura/hasura-metadata/tables.yaml
hooks/emitter/oracle.go
hooks/emitter/staking.go

- Add last_request for Oracle script and data source.
- Add stats for requests of each os and ds per day.
- Add view to query last 1 day of number of requests of ds.
- Fix jail status for unbonding case
```sql
ALTER TABLE oracle_scripts ADD last_request timestamp WITHOUT TIME ZONE;
ALTER TABLE data_sources ADD last_request timestamp WITHOUT TIME ZONE;
CREATE TABLE oracle_script_requests_per_days (
date DATE NOT NULL, 
oracle_script_id INTEGER NOT NULL, 
count INTEGER NOT NULL, 
PRIMARY KEY (date, oracle_script_id), 
FOREIGN KEY(oracle_script_id) REFERENCES oracle_scripts (id)
)
CREATE TABLE data_source_requests_per_days (
date DATE NOT NULL, 
data_source_id INTEGER NOT NULL, 
count INTEGER NOT NULL, 
PRIMARY KEY (date, data_source_id), 
FOREIGN KEY(data_source_id) REFERENCES data_sources …
```

[Extra/rest 2.5] Add stats for os and ds, Fix jail status

---

flusher/flusher/db.py
flusher/flusher/handler.py
hasura/hasura-metadata/tables.yaml

Table relayer_tx_stat_days
| Column 1 | Type |  |
| -------- | -------- | -------- |
| date     | CustomDate     | PK     |
| port     | String     | PK, FK   |
| channel     | String     | PK, FK     |
| address     | String     | PK     |
| ibc_received_txs     | Integer     |     |
| last_update_at     | CustomDateTime     |     |
> Note: 
> ```
> CREATE TABLE RELAYER_TX_STAT_DAYS(
>   DATE DATE NOT NULL,
>   PORT VARCHAR (20) NOT NULL,
>   CHANNEL VARCHAR (20) NOT NULL,
>   ADDRESS  VARCHAR (255) NOT NULL,
>   IBC_RECEIVED_TXS INT,
>   LAST_UPDATE_AT TIMESTAMP,
>   CONSTRAINT PK_RELAYER_STATS PRIMARY KEY (DATE,PORT,CHANNEL,ADDRESS),
>   FOREIGN KEY (PORT,CHANNEL) REFERENCES CHANNELS(PORT,CHANNEL)
>);
> ```

[Extra/rest 2.5] add relayer stat

---

README.md
app/app.go
testing/chain.go
testing/endpoint.go
x/globalfee/README.md
x/oracle/client/cli/tx.go
x/oracle/ibc_test.go
x/oracle/module.go
yoda/README.md
yoda/executor/executor.go
yoda/gas.go

Fixed:
- Revisit document
- Revisit TODO

Revisit todo readme

---

go.mod
go.sum

Fixes Ledger signing problems on by updating to newer versions of hid, ledger-go and ledger-cosmos-go.
Older versions result in an empty `Error: ` message when attempting to sign transactions with a Ledger and bandd binary.
Same issue is described (and same fix merged) to Cosmos Gaia repo: https://github.com/cosmos/gaia/pull/2763

chore: ledger dependency

---

hooks/emitter/channel.go
hooks/emitter/handler.go

- Add handle for MsgTimeout on channel module
- Add packet sender account to accountInTx to update balance

[fix] Handle MsgTimeout and update balance when fail to send packet

---

pkg/obi/decode.go
testing/ibctesting/chain.go
testing/ibctesting/coordinator.go

chore: fix some function names

---

grogu/signaller/signaller.go
grogu/signaller/signaller_test.go
grogu/signaller/utils.go
grogu/signaller/utils_test.go

- tracking for change in price status in `shouldUpdatePrice` function
- handle divide by zero case in deviation check
- update unit tests

[Fix][Feeds] Fix Grogu

---

x/feeds/keeper/grpc_query_test.go
x/feeds/keeper/keeper_price.go
x/feeds/keeper/keeper_price_test.go

Fixed:
- use blocktime as a timestamp for default of price (not in current feeds)

[fix][feed] use blocktime for default timestamp instead of 0

---

hooks/emitter/bank.go
hooks/emitter/handler.go

- add sender account in case use bank keeper to send coins

[Extra/rest] Add sender account in case use bank keeper to send coins

---

README.md
cylinder/README.md
yoda/README.md

This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected `drop as a line` to `drop us a line`
Corrected `gad` to `gas`
Corrected `by user` to `by the user`
Please review the changes and let me know if any additional changes are needed.

fix: typos in documentation files

---

Dockerfile.static

Fixed:
- Update checksum of go-owasm in Dockerfile

Update checksum of go-owasm in Dockerfile

---

flusher/flusher/feeds_db.py
flusher/flusher/handler.py
hooks/emitter/feeds.go

- add field tx id to validator prices db
- command for altering existing table
```
ALTER TABLE feeds_validator_prices
ADD COLUMN transaction_id INTEGER,
ADD CONSTRAINT feeds_validator_prices_transaction_id_fkey
FOREIGN KEY (transaction_id)
REFERENCES transactions (id);
```

[Feeds] Add tx id in validator prices db

---

pkg/filecache/filecache_test.go

`TempDir()` is a method introduced in Go 1.15 for `testing.T`. It automatically creates a temporary directory and cleans it up after the test is complete, eliminating the hassle of manually handling errors and cleanup.
More info about TempDir  https://pkg.go.dev/testing#B.TempDir

refactor: use t.TempDir() instead of os.MkdirTemp

---

cmd/cylinder/export.go
cmd/cylinder/import.go
cmd/cylinder/main.go
cmd/cylinder/run.go
cylinder/context/context.go
cylinder/store/store.go

Fixed:
- Fix cylinder initializing DB to be able to run in parallel (init db only in command `run`, `import`, `export`).

[Cylinder] Fix cylinder db

---

x/oracle/keeper/report.go
x/oracle/keeper/signing.go
x/oracle/simulation/genesis_test.go
x/tss/keeper/keeper_signing_endblock.go

chore: fix function name in comment

---

app/hooks.go
hooks/emitter/decoder_test.go

Fixed: 
- Events lacking the "mode" key as their final attribute are treated as originating from initGenesis and classified as BeginBlock events.

[Extra/rest] support events that emitted during initGenesis

---

app/upgrades/v3/upgrades.go
cmd/bandd/cmd/root.go

- Add baseapp options for disable-iavl-fast-node and query-gas-limit 
- Add migration on consensusparam when upgrade

Add fastnode baseapp options and consensusparam migration

---

pkg/bandrng/sampling.go

Optimize code using a more modern writing style. Official support from Go, for more details visit https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize.

refactor: replace append slice manipulation with slices.Delete
