- x/oracle/keeper/grpc_query.go
- x/oracle/keeper/keeper.go
- x/oracle/keeper/querier.go
- x/oracle/keeper/querier_test.go
- x/oracle/types/querier.go
> Patch querier and add grpc query

- docker-config/start_docker.sh
> fix make faucet

- app/app.go
- cmd/bandd/cmd/genos.go
- cmd/bandd/cmd/root.go
- go.mod
- go.sum
- x/oracle/keeper/keeper.go
- x/oracle/keeper/oracle_script.go
- x/oracle/keeper/oracle_script_test.go
- x/oracle/keeper/owasm.go
- x/oracle/testapp/setup.go
- x/oracle/testapp/wasm_util.go
> Upgrade go-owasm lib and add cache option

- yoda/execute.go
Add more condition on yoda's broadcasting tx. Yoda should consider codeSpace to prevent code overlapped with other module's errors.
Fixed: BAND-139
Adjust condition on transaction code by also considering transaction's codeSpace.
> Yoda - Fix condition on out-of-gas scenario

- go.sum
- proto/oracle/v1/genesis.proto
- proto/oracle/v1/oracle.proto
- proto/oracle/v1/query.proto
- proto/oracle/v1/tx.proto
- x/oracle/types/genesis.pb.go
- x/oracle/types/oracle.pb.go
- x/oracle/types/query.pb.go
- x/oracle/types/query.pb.gw.go
- x/oracle/types/tx.pb.go
This PR adds comments to Protobuf files to provide more information and help understanding data structure of the Protobuf messages.
**No code, only comments.**
> Add protobuf comments for oracle modules

- app/app.go
Fixed: [BAND-280](https://bandprotocol.atlassian.net/browse/BAND-280)
This PR adds IBC's `transfer` module module to `BandApp` to allow sending tokens across chains.
> Add IBC's transfer app to Bandchain

- app/genesis.go
> Fix Genesis for transfer module

- hooks/emitter/emitter.go
- hooks/emitter/staking.go
> Remove debug log

- x/oracle/types/params.go
Base on the research result we use ~340 us to execute empty OWASM and our target gas price is 50 gas/us
So we should collect gas ~17000 and then we decide to use 20000 as the base OWASM gas.
- Patch base owasm gas
> Patch base owasm gas

- cmd/bandd/cmd/migrate.go
- cmd/bandd/cmd/root.go
- go.mod
- proto/oracle/v1/genesis.proto
- proto/oracle/v1/oracle.proto
- proto/oracle/v1/query.proto
- proto/oracle/v1/tx.proto
- x/oracle/types/genesis.pb.go
- x/oracle/types/oracle.pb.go
- x/oracle/types/query.pb.go
- x/oracle/types/query.pb.gw.go
- x/oracle/types/tx.pb.go
> Command for migrate guanyu to laozi (cosmos part)

- x/oracle/module.go
> Return err instead of ack when receiving a random packet data

- flusher/flusher/handler.py
- flusher/flusher/init.py
- hooks/emitter/oracle.go
> Fix flusher to flush os ds stat

- hooks/emitter/gov.go
- hooks/emitter/handler.go
- hooks/emitter/staking.go
> Emitter: fix bug extra field

- docker-compose.yaml
- docker-config/start_docker.sh
- proxy/Dockerfile
- proxy/default.vcl
> Add vanish for docker-compose

- flusher/flusher/handler.py
> Emitter: Fix bug remove reporter

- flusher/flusher/db.py
- flusher/flusher/init.py
> Emitter: optimize oracle response time query

- x/oracle/keeper/owasm_test.go
- x/oracle/keeper/request_test.go
- x/oracle/keeper/result.go
- x/oracle/keeper/result_test.go
- x/oracle/types/packets_test.go
- x/oracle/types/result_test.go
Noted! This pr break the consensus of current testnet!! We will use `laozi-testnet` branch for release update on testnet. Please don't use the master running the node.
> Change result encode by codec instead of OBI

- yoda/main.go
> Add `yoda version` command

- x/oracle/ibc_test.go
- x/oracle/keeper/request_pool.go
- x/oracle/keeper/request_pool_test.go
Fixed: #100 
Fix typo of the keeper function name.
> Fix keeper typo

- x/oracle/handler_test.go
- x/oracle/keeper/msg_server.go
> HOTFIX: fix edit data source and oracle script

- testing/testapp/setup.go
- x/oracle/ibc_test.go
- x/oracle/keeper/owasm_test.go
- x/oracle/keeper/relay.go
- x/oracle/module.go
- x/oracle/types/constants.go
- x/oracle/types/error.go
- x/oracle/types/msgs.go
- x/oracle/types/packets.go
> refactor + new ibc validatebasic test

- x/oracle/keeper/msg_server.go
> Fix bug msg server reporter

- x/oracle/types/expected_keepers.go
> remove ChanCloseInit from channel expected keeper

- .github/workflows/update-extra-rest.yaml
This github action automatically updates `extra/rest` branch when something has been pushed on master.
> Add workflow file

- hooks/emitter/decoder.go
- hooks/emitter/decoder_test.go
Fixed: #XXXX
- Add emitter decoder for gov & staking messages
> Emitter decoder [gov & staking msgs]

- hooks/price/price.go
- hooks/request/request.go
- x/oracle/client/cli/query.go
> Change Calldata of QueryRequestSearchRequest to be Hex Format Instead

- cmd/bandd/cmd/root.go
add feeless reports flag for start cmd
> bind feeless flag

- hooks/emitter/decoder.go
- hooks/emitter/decoder_test.go
> Emitter: IBC message decoder

- hooks/emitter/channel.go
> Fix bug emitter must get request

- hooks/request/db.go
- hooks/request/types.go
Fixed: -
**Update**: Use CASCADE and add flag `_foreign_keys=on` flag to sqlite3 instead.
If SQLite is used for storing oracle requests, foreign keys PRAGMA, by default, are disabled, which `CASCADE` constraint will not be effected. Therefore, historical data deletion should be re-implemented to delete all associated records on all tables based on given request IDs.
Furthermore, when foreign key PRAGMA are disabled, key indexing on those columns are ignored, so we need to specifically added index for those association columns.
`deleted_at` is also removed from database since it is unused in this scenario, which improves query performance as `deleted_at IS NULL` is dissappeared.
> Improve Request Search DB Queries

- cmd/bandd/cmd/init.go
- cmd/bandd/cmd/migrate.go
Increase max bytes when init and migrated genesis file
> Increase max bytes for evidence

- go.mod
- go.sum
- x/oracle/keeper/owasm.go
- x/oracle/types/exec_env.go
- x/oracle/types/exec_env_test.go
Fixed: #XXXX
- add GetPrepareTime() and GetExecuteTime() functionality for oracle script VM
> add oei time

- hooks/emitter/authz.go
- hooks/emitter/handler.go
- hooks/emitter/oracle.go
> Implement emitter handle authz

- hooks/emitter/authz.go
> emitter: remove report authorization

- hooks/emitter/decoder.go
- hooks/emitter/decoder_test.go
> Authz decoder

- docker-config/start_docker.sh
> Fix start docker script

- docker-config/start_docker.sh
> Fix start docker yoda part

- flusher/flusher/db.py
> Fix amount in redelegation table

- flusher/flusher/db.py
- hooks/emitter/staking.go
> Patch delegation event

- flusher/flusher/handler.py
> flusher: Fix reporter

- CHANGELOG.md
- cmd/faucet/handler.go
- go.mod
- go.sum
- yoda/execute.go
> Patch extra rest to cosmos v0.44.0

- x/oracle/ante/ante.go
> Allow whitelist execute MsgExec

- hooks/emitter/emitter.go
> Fix bug related transaction

- hooks/emitter/handler.go
> Emitter: disable gov module

- README.md
> Fix url in Readme.md

- CHANGELOG.md
- yoda/context.go
- yoda/keys.go
- yoda/main.go
- yoda/run.go
-  [x] The pull request includes a description of the implementation/work done in detail.
> Fix Yoda run can't cache file

- hooks/emitter/channel.go
> emitter: fix bug duplicate packet sequence

- hooks/emitter/channel.go
- Add sender or receiver (only Band account) to txAccount to update band balance/and related tx.
> add sender/receiver of transfer token to account tx

- app/app.go
- cmd/bandd/cmd/root.go
- hooks/common/hook.go
- hooks/emitter/decoder.go
- hooks/emitter/decoder_test.go
- hooks/emitter/emitter.go
- hooks/price/price.go
- hooks/request/request.go
- testing/testapp/setup.go
- x/oracle/keeper/grpc_query.go
- x/oracle/keeper/keeper.go
- x/oracle/module.go
Fixed: #XXXX
- Create hook in app instead of cmd
- Send hook to oracle module using in Querier
> Fix request hook

- app/app.go
- docker-config/hasura-metadata/tables.yaml
- flusher/flusher/db.py
- flusher/flusher/handler.py
- hooks/emitter/channel.go
- hooks/emitter/emitter.go
- hooks/emitter/handler.go
- store incoming_packets for ICA host packet
- handle inner messages of ICA packet
- add interchain_accounts in the flusher init and Hasura metadata
- store mapping interchain_accounts in the table
- [] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
> Add emitter for ICA host message

- app/app.go
- cmd/bandd/cmd/genos.go
- cmd/bandd/cmd/root.go
- fixed typo for ProposalHandler (it's just client-side command. doesn't affect the chain.)
- fixed typo of description for "add-oracle-script" command.
> Fix typo of description and client command

- app/app.go
- cmd/bandd/cmd/genos.go
- cmd/bandd/cmd/root.go
- update typo for extra/rest (use code from https://github.com/bandprotocol/chain/pull/215)
> Update typo for extra/rest

- app/app.go
- pkg/filecache/filecache.go
- pkg/gzip/gzip.go
- pkg/gzip/gzip_test.go
- testing/testapp/setup.go
- x/oracle/keeper/snapshotter.go
- x/oracle/keeper/snapshotter_integration_test.go
- add snapshot extension for oracle module (use code from https://github.com/bandprotocol/chain/pull/217)
- fixed conflict
> add snapshot oracle from master and fixed conflict

- go.sum
- x/oracle/keeper/grpc_query.go
- x/oracle/keeper/grpc_query_test.go
- x/oracle/types/expected_keepers.go
add reporters query for validator to query their granted reporters via grpc query
> Reporter query

- CHANGELOG.md
> update unrelease changelog

- x/oracle/keeper/grpc_query.go
> Extra rest add change log 2.3.4

- CHANGELOG.md
- x/oracle/keeper/grpc_query.go
- x/oracle/keeper/grpc_query_test.go
- x/oracle/types/expected_keepers.go
- add reporter query
- add changelog
> Add reporter query and changelog from master

- hooks/emitter/staking.go
Fixed:
- Fix validator missing for emitter
> Fix validator missing for emitter

- flusher/flusher/handler.py
- hooks/emitter/staking.go
Fixed: 
- Adjust diff for extra rest 2.3
> Adjust diff for extra rest 2.3

- flusher/flusher/db.py
- flusher/requirements.txt
Fixed:
- update typed-ast version
- use b64.decodebytes instead of b64.decodestring
> fixed depedency version

- yoda/execute.go
- update yoda to broadcast by sync mode
> [v2.3.x] Change yoda to use sync mode

- yoda/execute.go
- update yoda to broadcast by sync mode.
> Update yoda to use sync mode

- hooks/emitter/authz.go
- hooks/emitter/channel.go
- hooks/emitter/decoder.go
- hooks/emitter/decoder_test.go
- hooks/emitter/emitter.go
- hooks/emitter/handler.go
- hooks/emitter/oracle.go
- updated emitter logic for MsgExec to handle and decode the actual messages correctly.
> Update emitter logic for MsgExec

- .github/workflows/ci.yaml
- .github/workflows/golangci-lint.yml
- .golangci.yml
- Dockerfile
> Update go version in CI

- x/oracle/abci.go
- x/oracle/types/constants.go
- Remove parallel for resolving requests at end block.
- [] The pull request includes any and all appropriate unit/integration tests
> Remove parallel for resolving requests at endblock

- CHANGELOG.md
- go.mod
- go.sum
> Bump go-owasm version

- CHANGELOG.md
- go.mod
- go.sum
- yoda/execute.go
> Update extra-rest v2.3 from release v2.3

- flusher/flusher/db.py
- hooks/emitter/gov.go
- hooks/emitter/oracle.go
- add logic for emitter to decode the content of MsgSubmitProposal
- add logic for emitter to put version into oracle_scripts table
- add content column for proposal table
- add version column for oracle_scripts table
> Update emitter to store decoded content and version of oracle scripts

- flusher/flusher/db.py
- hooks/emitter/gov.go
- hooks/emitter/oracle.go
- Update emitter v2.3 to support oracle_script version and content of proposal
> Update emitter v2.3 to support oracle_script version and content of proposal

- CHANGELOG.md
- go.mod
- go.sum
> Bump go-owasm to 0.2.1

- app/app.go
- Fixed client command for software-upgrade (it's just client-side command. doesn't affect the chain.)
> Fixed client command for software-upgrade

- client/validators.go
- Add context in /validators api
> Add context in /validators api

- client/validators.go
- Add context in /validators api
> [Extra/rest] Add context in /validators api

- flusher/flusher/db.py
- flusher/flusher/handler.py
- hooks/emitter/decoder.go
- hooks/emitter/emitter.go
Fixed: add feegrant and fee_payer support
You have to add column "fee_payer" using this SQL command
ALTER TABLE transactions ADD COLUMN fee_payer VARCHAR;
> add feegrant support and fee_payer

- cmd/faucet/handler.go
- cmd/faucet/rate_limit.go
- cmd/faucet/run.go
- go.mod
- go.sum
- add rate limit per ip to faucet for spam prevention
> [Extra rest] Add rate limit for faucet

- app/ante.go
- app/app.go
> Add ante from ibc

- .github/workflows/release.yaml
- Dockerfile.alpine
- Dockerfile.static
- Makefile
- go.mod
- go.sum
- Adjust Makefile to support flags for statically linked binary
- Add dockerfile for building statically linked bandd
- Add GitHub action to build binary and attach it into release tags.
**Note**:  
- ~~Currently, it uses go-owasm from the test version (v0.2.2-static-test) as there is no official version with provided static libs yet.~~ updated to v0.2.3
- ~~After this PR (https://github.com/bandprotocol/go-owasm/pull/20) is merged and tag the official version, need to update this PR to use that version instead.~~  updated
> Statically linked Bandd for linux x86_64

- cmd/bandd/cmd/root.go
- testing/testapp/setup.go
- x/oracle/keeper/snapshotter.go
- x/oracle/keeper/snapshotter_integration_test.go
Fixed:
- add snapshot logic back
> [cosmos 0.46] add snapshot logic back

- CHANGELOG.md
- client/client.go
- x/oracle/client/rest/rest.go
> [2.5] Add new path for rest query

- CHANGELOG.md
> [2.5] Add changelog

- docker-compose.yaml
- docker-config/run.sh
- docker-config/start_docker.sh
- flusher/Dockerfile
- proxy-ssl/nginx.conf
- proxy/default.vcl
- use container name instead of fixed ip
- adjust path for proxy-ssl
- [] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
> [Extra/rest 2.4] improve docker configuration

- flusher/flusher/db.py
- flusher/flusher/handler.py
- hooks/emitter/channel.go
- Add last_update column for channels based on incoming and outgoing packets
Note:
- ALTER TABLE public.channels ADD last_update timestamp WITHOUT TIME ZONE NOT NULL;
- CREATE INDEX ix_channels_last_update ON public.channels (last_update)
> [Extra/rest 2.4] Add last_update column for channels

- CHANGELOG.md
- go.mod
- go.sum
- Patch cosmos-sdk 0.45.16 
- Patch ibc-go 4.3.1
- Patch cometbft 0.34.28
> Patch cosmos-sdk 0.45.16 / ibc-go 4.3.1 / cometbft 0.34.28

- CHANGELOG.md
- go.mod
- go.sum
> [Extra-rest 2.5] Patch dependency version

- hooks/emitter/authz.go
- update handler of MsgExec to use sub detail. (This will help sub-messages of exec has the same detail structure as normal messages)
> [Extra/rest 2.5] update handler of MsgExec to use sub detail

- hooks/price/price.go
- hooks/price/types.go
- hooks/price/types_test.go
- Implement decode result to support new obi result format
- add test
> [Extra/rest 2.5] support new obi result

- flusher/flusher/db.py
- flusher/requirements.txt
- Align on the name of index
- Use the same with current db
- [] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
> [Extra/rest 2.5] Update schema of db

- app/genesis.go
Fixed:
- Use default genesis from govv1 instead of govv1beta1
> [Main] Use default genesis from govv1 instead of govv1beta1

- .clang-format
- proto/bandchain/v1/node/query.proto
- proto/bandchain/v1/oracle/proof.proto
- proto/globalfee/v1beta1/genesis.proto
- proto/globalfee/v1beta1/query.proto
- proto/oracle/v1/genesis.proto
- proto/oracle/v1/oracle.proto
- proto/oracle/v1/query.proto
- proto/oracle/v1/tx.proto
- x/oracle/types/genesis.pb.go
- Add formatter for the proto files (use same config with Cosmos SDK)
> Add formatter for proto file

- go.mod
- go.sum
> bumb cometbft to 0.34.29

- CHANGELOG.md
- yoda/event.go
- yoda/handler.go
- yoda/run.go
Fixed:
- Update yoda to rely on data from request_id instead of event
> Update yoda to rely on data from request_id instead of event

- yoda/context.go
- yoda/execute.go
- yoda/run.go
Fixed:
- Remove cache of data source hash in Yoda
> [Yoda] Remove cache of data source hash in Yoda

- yoda/context.go
- yoda/execute.go
- yoda/run.go
> [Main] Patch update from v2.5.4

- SECURITY.md
- add security.md for contacting about vulnerability.
- [] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
> [chore] Add security.md file

- .github/workflows/ci.yaml
- .github/workflows/golangci-lint.yml
- .github/workflows/simulation.yml
- .golangci.yml
- CHANGELOG.md
- Dockerfile
- Dockerfile.static
- contrib/devtools/Dockerfile
- go.mod
> [chore] Use go 1.22.3

- .golangci.yml
- Makefile
- benchmark/app_test.go
- benchmark/helper_test.go
- scripts/generate_genesis.sh
- scripts/group/create_group.sh
- scripts/group/create_policy.sh
- scripts/group/group_members.json
- scripts/group/threshold_policy.json
- scripts/mockgen.sh
- remove unused code
- add mock gen command
- add chain_id in benchmark test
- add group module script for testing
- add account in genesis testing file
- adjust voting_period in genesis testing file
> [chore] Cleanup code

- app/params/doc.go
- app/upgrades/types.go
- testing/ibctesting/endpoint.go
- x/oracle/keeper/oracle_script_test.go
- x/oracle/keeper/report_test.go
- x/oracle/types/keys.go
> chore: fix some comments

- app/app.go
- app/genesis.go
- app/keepers/keepers.go
- app/upgrades/v2_6/constants.go
- add ibcfee module
- adjust ibc stack for transfer and icahost to support ibcfee
> [feat] Add ibcfee module

- x/feeds/keeper/keeper_price.go
- x/feeds/keeper/keeper_price_test.go
- x/feeds/types/median.go
- x/feeds/types/median_test.go
- x/feeds/types/msgs.go
- update median uint64 to sdkmath.Int
- more validation for signal price status
> [Fix] Fix Feeds Module

- yoda/execute.go
- yoda/run.go
Fixed:
- fix query path for yoda since the proto path has changed with `band` prefix.
> [fix] Query path on yoda

- grogu/submitter/submitter.go
- x/feeds/keeper/msg_server.go
- check signal prices against current feeds instead of param
> [Fix] Feeds Module

- flusher/flusher/db.py
Fixed:
- Add nullable for time field in proposal
> [Extra/rest] Add nullable for time field in proposal

- docker-config/bothan-config.toml
> [Fix] fix bothan config

- scripts/tunnel/trigger_tunnel.sh
- x/tunnel/client/cli/tx.go
- update trigger tunnel script
> [Tunnel] update trigger tunnel script

- scripts/generate_genesis.sh
- scripts/tunnel/create_tunnel.sh
- x/tunnel/types/params.go
> [Tunnel] fix params and add genesis script

- x/bandtss/keeper/keeper.go
- x/bandtss/keeper/msg_server.go
- x/feeds/keeper/msg_server.go
- x/restake/keeper/msg_server.go
- x/tss/keeper/msg_server.go
- x/tunnel/keeper/keeper.go
- x/tunnel/keeper/msg_server.go
> [chore] add keeper call

- grogu/signaller/signaller_test.go
- sort signalIDs to ensure order when testing
> [Fix][Grogu] fix signaller test

- x/tunnel/types/codec.go
> [Tunnel] add IBC interface

- proto/band/base/oracle/v1/proof.proto
> [Fix] update proto

- grogu/signaller/signaller_test.go
- sort signalIDs from map to ensure order
> [Fix] fix signaller test

- flusher/flusher/handler.py
- flusher/flusher/tss_db.py
- hasura/hasura-metadata/tables.yaml
- hooks/emitter/bandtss.go
- hooks/emitter/handler.go
- hooks/emitter/tss.go
Fixed: 
- remove encoded_originator from tss_signings. 
- remove bandtss members when active group has been replaced.
> [Extra/rest] fix bandtss/tss db

- x/feeds/README.md
- update readme to contain new params, explanation to price status and validator price status, more detail on price calculation
> [Feeds] update readme

- x/tss/keeper/keeper_signing_query.go
Fixed:
- fix bug query path (current it will return only one pending)
> [tss] fix pending signing query issue

- x/tunnel/README.md
> [Tunnel] Add TSS Route on Readme

- api/band/bandtss/v1beta1/genesis.pulsar.go
- api/band/oracle/v1/oracle.pulsar.go
- api/band/tss/v1beta1/genesis.pulsar.go
- x/bandtss/types/genesis.pb.go
- x/oracle/types/oracle.pb.go
- x/tss/types/genesis.pb.go
> [chore] Re-generate proto files

- x/feeds/README.md
- x/tss/README.md
- x/tunnel/README.md
- x/tunnel/keeper/keeper_packet.go
- yoda/README.md
> fix: typos

- x/feeds/keeper/keeper_price.go
- x/oracle/client/cli/tx.go
- x/oracle/keeper/report.go
fix some function names in comment
> chore: fix some function names in comment

- scripts/start_yoda.sh
The word "addding" contains an extra "**d**."
corrected
> docs: typo Update start_yoda.sh

- x/tunnel/keeper/helper.go
- x/tunnel/keeper/keeper_packet.go
Fixed: 
- check recover result if it is a panic due to out of gas error during sending a packet.
> [Tunnel] fix recover out of gas error

- CHANGELOG.md
- scripts/start_grogu.sh
- scripts/tunnel/update_and_reset_tunnel.sh
- x/bandtss/keeper/keeper_signing_test.go
- x/bandtss/keeper/msg_server_test.go
- x/bandtss/types/params.go
- x/tunnel/client/cli/tx.go
- x/tunnel/types/params.go
Fixed:
- adjust wording, changelog, and params.
- update the test to be more flexible.
> Adjust wording, params

- x/feeds/keeper/keeper_price.go
- x/feeds/keeper/keeper_price_test.go
- x/feeds/types/constant.go
Fixed:
- Change GuaranteeBlockTime for feeds module from 3 to 1 sec.
> Change GuaranteeBlockTime for feeds module from 3 to 1 sec.

- app/params/amino.go
- app/params/encoding.go
- app/params/proto.go
- cmd/bandd/cmd/root.go
- cmd/cylinder/root.go
- cmd/grogu/cmd/run.go
- cmd/grogu/main.go
- grogu/context/context.go
- grogu/submitter/submitter_test.go
- yoda/context.go
- yoda/execute.go
- yoda/gas.go
- yoda/main.go
- yoda/run.go
Fixed:
- fix logic to delete tempdir of temp application.
> [Main] Fix tempdir deletion issue

- app/upgrades/v3/upgrades.go
> update mint, slashing params

- .github/workflows/golangci-lint.yml
- .golangci.yml
Fixed:
- update lint version and config
> [chore] Update lint version and config

- flusher/flusher/db.py
- flusher/flusher/handler.py
- hooks/emitter/gov.go
- hooks/emitter/handler.go
Fixed: 
- support MsgCancelProposal
Note: `ALTER TYPE proposalstatus ADD VALUE 'Cancelled';`
> [Extra/rest] support MsgCancelProposal

- x/tunnel/keeper/keeper_packet_ibc_test.go
> update test to fixed value

- hooks/emitter/authz.go
Fixed: add MsgSubmitSignature, MsgSubmitDE into handleMsgExec func
> [Extra/rest] fix tss tx

- testing/testdata/wasm_extras.go
Fixed:
- remove init testdata because of unused
> chore: remove init testdata

- x/bandtss/abci.go
- x/feeds/abci.go
- x/oracle/abci.go
- x/rollingseed/abci.go
- x/tss/abci.go
- x/tunnel/abci.go
- Add metrics begin/end block for each module.
> [Telemetry] Add metrics begin/end block for each module.

- cmd/bandd/cmd/root.go
Fixed:
- Add default genesis path in newApp, so all other command that doesn't load config (e.g. prune) can create an app. 
- Ref: https://github.com/cosmos/cosmos-sdk/blob/v0.50.11/server/util.go#L516-L519
> [fix] Add default genesis path in newApp

- client/grpc/oracle/proof/service.go
Fixed: #XXXX
Modify proof service to return latest proof as latest canonical block
> [feat] Modify Proof Service

- benchmark/helper_test.go
- x/oracle/keeper/owasm.go
- x/oracle/keeper/snapshotter.go
In Go 1.21, the standard library includes built-in [max/min](https://pkg.go.dev/builtin@go1.21.0#max) function, which can greatly simplify the code.
> refactor: use the built-in max to simplify the code

- app/upgrades/v3/upgrades.go
- x/oracle/types/params.go
- adjust default oracle params MaxCalldataSize to 512
- set oracle params MaxCalldataSize to 512 in upgrade v3
- set oracle params MaxReportDataSize to 512 in upgrade v3
> adjust oracle params in upgrade

- cmd/grogu/cmd/run.go
- cmd/grogu/main.go
- grogu/context/context.go
- grogu/signaller/signaller.go
Fixed: 
- grogu context in command functions
- use time.Duration in config
- use time.ticker instead of time.sleep
> [Grogu] fix interval trigger

- grogu/TELEMETRY.md
> [grogu] add telemetry docs

- x/bandtss/client/cli/tx.go
Fixed: 
- fix bandtss activate command to support activation on both groups.
> [TSS] fix bandtss activate tx command

- api/band/base/node/v1/query.pulsar.go
- client/grpc/node/query.pb.go
- proto/band/base/node/v1/query.proto
from #558 fix on proto file and re-generate files
> [chore] fix typo

- yoda/execute.go
- implement response code checking in yoda tx broadcasting
> [Fix] fix yoda not checking response code

- app/app.go
- app/lanes.go
- app/mempool/mempool.go
Fixed: Invalid block sequence
- Created a custom CheckTx method for the chain to remove invalid transactions.
> [Fix][Mempool] Fix invalid block sequence

- cmd/grogu/cmd/run.go
- grogu/telemetry/collector.go
- grogu/telemetry/telemetry.go
- grogu/updater/updater.go
- scripts/start_grogu.sh
Fixed: 
- add labels into metrics
> [Grogu] Fix telemetry

- x/feeds/types/median.go
- x/oracle/types/packets.go
- yoda/executor/multi.go
> chore: fix some typos in comment

- flusher/flusher/feeds_db.py
- make operator_address in feeders table as foreignkey
- remove index from primary key
> [Fix] Fix feeds db

- app/mempool/README.md
- app/mempool/lane.go
- Add README for mempool
- make a function private for lane
> [Mempool] Add Readme

- cylinder/context/context.go
- cylinder/workers/de/de.go
- scripts/bandtss/start_cylinder.sh
- add update config in the script
> [cylinder] add config query de interval

- app/ante.go
- app/app.go
- app/lanes.go
- app/match.go
- app/mempool/lane.go
- app/mempool/lane_test.go
- app/mempool/mempool_test.go
- app/mempool/types.go
Refactor match function in lane reduce duplicate logic
> [chore] Refactor match fn in lane

- app/mempool/lane.go
- app/mempool/lane_test.go
- app/mempool/mempool.go
- app/mempool/mempool_test.go
- app/mempool/proposal.go
- move tx size check to lane insertion
- add test for tx bytes
> [Fix][Mempool] Fix Tx size validation

- cmd/cylinder/remove_unused_de.go
- cmd/cylinder/root.go
- cylinder/client/client.go
Fixed: 
- add remove-unused-de command
> [Cylinder] add remove-unused-de command

- go.mod
- go.sum
Fixed: 
- update bothan-api/client version
> [Grogu] update bothan-api/client version

- Dockerfile
- cylinder/workers/de/de.go
- cylinder/workers/de/delete_de.go
- cylinder/workers/de/update_de.go
Fixed:
- fix DE worker, separate from DeleteDE and UpdateDE (since multiple subscriptions on the same client causes an issue on retry when connection loses)
> [Cylinder] fix de worker

- cmd/cylinder/run.go
- cmd/cylinder/status.go
> [cylinder] add /n when run cmd

- CHANGELOG.md
Fixed: adjust changelog detail for v3.0.0-rc3
> Add changelog for v3.0.0-rc3

- cmd/grogu/cmd/run.go
- cylinder/context/context.go
- grogu/context/context.go
- grogu/submitter/submitter.go
- grogu/submitter/submitter_test.go
- scripts/start_grogu.sh
- make gas adjustment and gas step config in grogu
- change default gas adjustment to 1.0
- put all config in start_grogu.sh script
> [chore] make gasadjustment a config in Grogu

- cmd/grogu/cmd/run.go
- scripts/start_grogu.sh
> [Fix][Grogu] change gas adjust start from 1.0 to 1.2

- grogu/telemetry/collector.go
- call telemetry success and failed update registry count when registry is updated
> fix grogu telemetry update registry

- api/band/oracle/v1/query_grpc.pb.go
- api/band/tss/v1beta1/tss.pulsar.go
- api/band/tunnel/v1beta1/route.pulsar.go
- app/params/doc.go
- cylinder/workers/group/round2.go
- pkg/tss/round2.go
- proto/band/oracle/v1/query.proto
- proto/band/tss/v1beta1/tss.proto
- proto/band/tunnel/v1beta1/route.proto
- x/bandtss/keeper/keeper_signing_test.go
- x/globalfee/feechecker/utils_test.go
- x/oracle/keeper/data_source_test.go
- x/oracle/keeper/request_test.go
- x/oracle/types/query.pb.go
- x/restake/README.md
- x/restake/keeper/keeper_lock.go
- x/tss/README.md
- x/tss/types/tss.pb.go
- x/tunnel/types/route.pb.go
- yoda/execute.go
- yoda/executor/multi.go
- yoda/run.go
Fixed: 
Fix typos using crate-ci/typos
> fix typo using crate-ci/typos

- scripts/test_script/3rc2_proposal.json
- scripts/test_script/open_vote_proposal_3rc2.sh
- scripts/test_script/runbook_25_3.sh
- scripts/test_script/runbook_3rc2_3rc3.sh
- add test script for upgrade v2.5 to v3
- add test script for upgrade v3.rc2 to v3.rc3
> add upgrade v3 test script

- cylinder/README.md
- scripts/bandtss/start_cylinder.sh
> [cylinder] adjust max-message from 20 to 10

- app/lanes_test.go
- x/bandtss/keeper/keeper_test.go
- x/tss/testutil/group_context.go
> [Mempool] add tss test

- app/app.go
- app/upgrades/v3/upgrades_test.go
- app/upgrades/v3_rc3/upgrades_test.go
- app/upgrades/v3_rc4/constants.go
- app/upgrades/v3_rc4/upgrades.go
- app/upgrades/v3_rc4/upgrades_test.go
- testing/test_helpers.go
- Assign the minter permission to the tunnel module account for IBC hook route functionality.
> Init upgrade handler v3.0.0-rc4

- cmd/grogu/cmd/keys.go
- cmd/grogu/cmd/run.go
- grogu/signaller/signaller.go
- grogu/signaller/signaller_test.go
- grogu/signaller/utils.go
- grogu/signaller/utils_test.go
- scripts/start_grogu.sh
- yoda/keys.go
- cleanup
- remove buffer cooldown time (since we already used block_time instead)
- change offset distribution to 25%
- change offset deadline to 15 sec
- compare unix timestamp on cooldown instead of using time object (to have same logic with on-chain)
> [grogu] cleanup, adjust config

- x/tss/client/cli/tx.go
replace Split in loops with more efficient SplitSeq
> refactor: replace Split in loops with more efficient SplitSeq

- go.mod
- go.sum
- grogu/signaller/testutil/expected_types_mock.go
- grogu/submitter/submitter.go
- grogu/submitter/submitter_test.go
- grogu/submitter/testutil/expected_types_mock.go
Fixed: 
- fix grogu to support new bothan client interface
> [Grogu] Support new bothan client interface

- grogu/submitter/submitter.go
Fixed:
- add goroutine for pushing monitoring record to prevent blocking feeder account to send new transaction if the bothan took long time.
> [grogu] add goroutine on push monitoring record

- app/ante.go
- skip `IgnoreDecorator` when simulate because it affects the gas calculation in simulation
> [Fix] Skip ignore decorator when simulate

- Dockerfile.static
- testing/testdata/wasm_util.go
- testing/testdata/wat2wasm_stub.go
- testing/testdata/wat2wasm_wasmtime.go
Fixed: 
- Exclude wasmtime from muslc build
> [chore] Exclude wasmtime from muslc build

- cylinder/client/client.go
- cylinder/context/context.go
- cylinder/parser/request_signature_event.go
- cylinder/parser/request_signature_event_test.go
- cylinder/workers/de/update_de.go
- cylinder/workers/signing/signing.go
Fixed: 
- add retry on query client of the cylinder object.
- use maxDEOnChain (being queried via tss params) instead of configuration.
- handle update DE properly
> [Cylinder] Upgrade cylinder

- pkg/tickmath/tickmath_test.go
> chore: fix function name

- cylinder/client/client.go
> [cylinder] add memo on transaction

- app/genesis.go
- app/upgrades/v3/constants.go
- app/upgrades/v3/upgrades.go
- app/upgrades/v3/upgrades_test.go
- x/bandtss/keeper/msg_server_test.go
- x/bandtss/types/params.go
- x/tss/keeper/keeper_group_endblock_test.go
- x/tss/types/params.go
- x/tunnel/types/params.go
- Adjust voting period, max deposit period, expedited voting period parameters for gov module on v3 upgrade
- Adjust tss module to allow max DE at 600
- Adjust max interval and deviation for tunnel module
> Adjust module parameters for v3 upgrade

- CHANGELOG.md
- app/app.go
- app/upgrades/v3_0_1_rc1_testnet/constants.go
- app/upgrades/v3_0_1_rc1_testnet/upgrades.go
- app/upgrades/v3_0_1_rc1_testnet/upgrades_test.go
Fixed:
- Adjust upgrade name for testnet
> Adjust upgrade name for testnet

- app/upgrades/v3/upgrades.go
- Add admin account of feeds on upgrade v3
> Add admin account of feeds on upgrade v3

- app/upgrades/v3/upgrades.go
- app/upgrades/v3/upgrades_test.go
- Update upgrade handler to migrate message name for grants
> Update upgrade handler to migrate message name for grants

- CHANGELOG.md
- go.mod
- go.sum
- bump iavl version
- add changelog
> [chore] bump iavl version
